#!/usr/bin/env python3
# Copyright 2026 robot-safety maintainer
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Launcher installed as ``lib/robot_safety_monitor/safety_gate``.

See the sibling ``monitor`` launcher for why an explicit file exists instead of
relying on the setuptools console script alone: ``ros2 run`` resolves executables
from ``lib/<package>/``.
"""

import sys

from robot_safety_monitor.safety_gate_node import main

if __name__ == '__main__':
    sys.exit(main())
